version: '3.9'

services:

  ldap:
    container_name: sds_ldap
    build:
      context: ./
    restart: unless-stopped
    ports:
      - "11389:11389"
      - "11636:11636"
    environment:
      LDAP_PORT_NUMBER: 11389
      LDAP_LDAPS_PORT_NUMBER: 11636
      LDAP_ENABLE_TLS: no
      BITNAMI_DEBUG: true
    volumes:
      # mount individual .ldif files to add data (bitnami won't find recursively, so you can't mount a subfolder)
      - ./more-ldifs/20_my_custom_users.ldif:/ldifs/20_my_custom_users.ldif:ro
      # mount individual schema extensions with a .ldif extension
#      - ./02_my_schema_extensions:/schemas/02_my_schema_extensions.ldif:ro


  ldap_ui:
    container_name: sds_ldap_ui
    image: dnknth/ldap-ui
    environment:
      LDAP_URL: "ldap://ldap:11389"
      BASE_DN: "o=nhs"
      BIND_DN: "cn=admin,o=nhs"
      BIND_PASSWORD: "adminpassword"
    ports:
      - "15000:5000"
    depends_on:
      - ldap